name: SLCUrban
favicon: null
layout_spectrum: 0.23415
typography_spectrum: 0.27066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.932085559470579
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
